name: hackatum-check24

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - benchmark
  benchmark:
    container_name: benchmark
    image: ghcr.io/havenousername/hackatum-check24-benchmark
    build:
      context: benchmark
      dockerfile: Dockerfile
    expose:
      - "3000"
  frontend:
    container_name: frontend
    image: ghcr.io/havenousername/hackatum-check24-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_BACKEND: 'http://nginx/benchmark'
      NEXT_PUBLIC_MAPS_API_KEY: 23Wx5lgtGMfDkfMkCuF1
